import type { Spec } from "./types";

const now = 0;

export const STARTER_SPECS: Spec[] = [
  {
    id: "starter-pancakes",
    title: "Simple pancakes",
    kind: "recipe",
    source: "starter",
    time: "20 minutes",
    servings: "makes about 8",
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "3 1/2 teaspoons baking powder",
      "1 tablespoon sugar",
      "1/2 teaspoon salt",
      "1 1/4 cups milk",
      "1 egg",
      "3 tablespoons melted butter, plus more for the pan",
    ],
    materials: [],
    steps: [
      "Whisk the flour, baking powder, sugar, and salt in a bowl.",
      "In another bowl, beat the milk, egg, and melted butter.",
      "Pour the wet mix into the dry mix and stir until just combined. A few lumps are fine.",
      "Heat a skillet over medium and add a little butter.",
      "Pour about a third of a cup of batter per pancake. Cook until bubbles form and the edges look set, then flip and cook the other side golden.",
      "Serve warm with butter and maple syrup.",
    ],
    spokenIntro:
      "Simple pancakes. About twenty minutes, eight pancakes. I'll read the ingredients first, then we'll cook step by step.",
    updatedAt: now,
  },
  {
    id: "starter-chili",
    title: "Weeknight chili",
    kind: "recipe",
    source: "starter",
    time: "45 minutes",
    servings: "4 bowls",
    ingredients: [
      "1 pound ground beef or turkey",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "1 red bell pepper, diced",
      "2 tablespoons chili powder",
      "1 teaspoon cumin",
      "1 teaspoon smoked paprika",
      "1 can kidney beans, drained",
      "1 can diced tomatoes, 28 ounce",
      "1 cup beef or chicken broth",
      "Salt and black pepper",
    ],
    materials: [],
    steps: [
      "Brown the meat in a heavy pot over medium-high heat. Break it up and cook until no longer pink.",
      "Add the onion and pepper. Cook until soft, about five minutes. Stir in the garlic for thirty seconds.",
      "Add chili powder, cumin, paprika, salt, and pepper. Stir until the spices smell toasted.",
      "Pour in the tomatoes, beans, and broth. Bring to a simmer.",
      "Turn the heat to low and cook uncovered for twenty-five minutes, stirring now and then, until thick.",
      "Taste for salt. Serve with shredded cheese, sour cream, or cornbread.",
    ],
    spokenIntro:
      "Weeknight chili. Forty-five minutes, four bowls. I'll start with what you need, then the steps.",
    updatedAt: now,
  },
  {
    id: "starter-eggs",
    title: "Soft scrambled eggs",
    kind: "recipe",
    source: "starter",
    time: "8 minutes",
    servings: "2",
    ingredients: [
      "4 eggs",
      "2 tablespoons milk or cream",
      "1 tablespoon butter",
      "Pinch of salt",
      "Black pepper",
    ],
    materials: [],
    steps: [
      "Crack the eggs into a bowl. Add milk, salt, and a little pepper. Beat until the yolks and whites are fully mixed.",
      "Melt the butter in a nonstick pan over low heat.",
      "Pour in the eggs. Let them sit for ten seconds, then push them slowly with a spatula from the edges toward the center.",
      "Keep folding gently over low heat until they look just set and still glossy. Take them off the heat before they look dry.",
      "Serve right away on warm toast.",
    ],
    spokenIntro:
      "Soft scrambled eggs for two. About eight minutes. Low heat is the whole trick.",
    updatedAt: now,
  },
  {
    id: "starter-knife",
    title: "Sharpen a kitchen knife",
    kind: "procedure",
    source: "starter",
    time: "10 minutes",
    servings: "",
    ingredients: [],
    materials: [
      "Whetstone or pull-through sharpener",
      "Damp towel",
      "Water if using a stone",
    ],
    steps: [
      "Set a damp towel under the stone so it cannot slide. If the stone needs soaking, soak it first per its instructions.",
      "Hold the knife at about fifteen to twenty degrees against the stone. That's a thin coin-stack angle.",
      "Push the blade away from you along the coarse side, heel to tip, with light even pressure. Repeat ten times.",
      "Do the same on the other side of the blade, same count, so you keep the edge centered.",
      "Switch to the fine side of the stone and repeat five strokes per side with almost no pressure.",
      "Wipe the blade clean. Test by slicing a piece of paper or a tomato skin. If it snags, give each side a few more light strokes.",
    ],
    notes: "Never run a knife along your hand to test the edge.",
    spokenIntro:
      "How to sharpen a kitchen knife. About ten minutes. We'll go slow and keep the angle steady.",
    updatedAt: now,
  },
  {
    id: "starter-oil-change",
    title: "Change the oil in a small engine",
    kind: "procedure",
    source: "starter",
    time: "25 minutes",
    servings: "",
    ingredients: [],
    materials: [
      "Correct oil for the engine, check the cap or manual",
      "Drain pan",
      "Funnel",
      "Rags",
      "Wrench for the drain plug if it has one",
    ],
    steps: [
      "Run the engine for two minutes so the oil is warm, then shut it off. Disconnect the spark plug wire on a mower or similar so it cannot start.",
      "Set a drain pan under the drain plug or dip the machine if it drains from the fill neck.",
      "Remove the drain plug or tip the machine per the manual. Let the oil drain fully.",
      "Reinstall the plug snug, not brutal. Wipe the area clean.",
      "Set the engine level. Fill with the listed amount of fresh oil through a funnel. Check the dipstick and stop at the full mark.",
      "Reconnect the spark plug wire. Start it, look for leaks, then shut it off and recheck the level.",
      "Take the used oil to a parts store or transfer station. Do not dump it.",
    ],
    spokenIntro:
      "How to change the oil in a small engine. About twenty-five minutes. Warm it first, then drain, then fill to the mark.",
    updatedAt: now,
  },
];
